### ISSUE TITLE
Add `get_or_none` method

### ISSUE THREAD

**Issue by MojixCoder** [aminalaee/mongox#22]
Hey, I'm planing to add `get_or_none` method to the `Queryset` class.  
Since most of the python ORMs have implemented this method, I think it's nice for us to have it too.  
What is your opinion?

**Comment by aminalaee** [comment]
Hey,

Thanks for the feedback.
We actually have that I think,

Model.query.first() will return first or None.
But Model.query().get() will get first or throw exceptions.

Does that make sense?

If you think it's not clear in the docs, we can improve that.

**Comment by MojixCoder** [comment]
I didn't know 'first' does that, so we don't need to do that.
Thank you

**Comment by aminalaee** [comment]
No worries.

Although I think we could have other shodtcuts like `get_or_create` or `update_or_create`.
They can be useful. If you feel like they're usable feel free to do them.
