### ISSUE TITLE
Querying inside lists

### ISSUE THREAD

**Issue by aminalaee** [aminalaee/mongox#31]
Need tests and probably fixes for querying inside a List field:

```python
import mongox


class Movie(mongox.Model):
    name: str
    year: int
   tags: List[str]
```

Need to be able to query inside the tags fields. Maybe like this:

```python
await Movie.query(Movie.tags == ["A", "B"])

await Movie.query(Q.contains(Movie.tags, ["A", "B"]))
```

Any feedback would be appreciated.

**Comment by MAD-py** [comment]
But I think we already have these two functionalities with:

```py
movie = await Movie.query(mongox.Q.in_(Movie.tag, ["test"])).get()
```

and

```py
movie = await Movie.query(Movie.tag == ["test", "test2"]).get()
```

What we can add would be something like this:

```py
movie = await Movie.query(Movie.tag in ["test"]).get()
```

Although it looks kind of weird.

What do you think?

**Comment by aminalaee** [comment]
Yeah I think for a start we need to have tests for it to make sure it works, and if not fix it.

And for the `Movie.query(Movie.name in ["x"])` I think it's pretty interesting. Would you mind creating a separate issue for following that? I want to keep them separated. What do you think?

**Comment by MAD-py** [comment]
Ofcourse, I will create the issue to talk about this.

and the other two ways I just tested and I think they work well, although we should create some good tests to not leave any case to out.

Do you want me to make them or do you take care of it?

**Comment by aminalaee** [comment]
Sure, you can do it.
It should be as simple as modifying the model and adding the test.

**Comment by MAD-py** [comment]
I found a case that I'm not quite sure if we should support it or not...

In mongoDB I have the following record.

```json
{
    "name": "Matrix Resurrections", 
    "year": 2021,
    "tags": ["Action", "Sci-Fi"]
}
```

and the query is

```py
movies = await Movie.query(Movie.tags == ["Sci-Fi", "Action"]).all()
```

Evidently it is the same data but the difference is the order of the tags, currently an empty list is returned, is this what we expected?

**Comment by aminalaee** [comment]
I think number 1 makes sense, if you compare two lists, the order should be considered.
But using `Q.in_` for a list doesn't look right to me. It's like doing `["Tag1", "Tag2"] in ["Tag1"]`. It's not what we want here.

But I was thinking that as part of this we need to introduce `Q.contains` and `Q.icontains`. something like:

```python
await Movie.query(Q.contains(Movie.tags, ["Action"]))
```

As an extra we can make `Q.contains` and `Q.icontains` work for strings too. We can discuss this later.

**Comment by aminalaee** [comment]
I think as you mentioned you're still interested to fix this, I'll assign it to you 👍

**Comment by MAD-py** [comment]
> I think number 1 makes sense, if you compare two lists, the order should be considered. But using `Q.in_` for a list doesn't look right to me. It's like doing `["Tag1", "Tag2"] in ["Tag1"]`. It's not what we want here.
> 
> But I was thinking that as part of this we need to introduce `Q.contains` and `Q.icontains`. something like:
> 
> ```python
> await Movie.query(Q.contains(Movie.tags, ["Action"]))
> ```
> 
> As an extra we can make `Q.contains` and `Q.icontains` work for strings too. We can discuss this later.

Ok, so I will be working on this in next few days.

**Comment by MAD-py** [comment]
Hey @aminalaee.

Last days I have been testing and searching how to build `Q.contains()`. So the issue is that it can be made with:

```py
movie = await Movie.query({Movie.tag: "Action"}).all()
```
Since mongo is in charge of doing the internal search in the list.

In addition, to search inside a string, the query in mongo would be something like this:

```
{"name": {$regex : "Boy"}}
```

so instead of creating a `Q.contains(Movie.name, "Boy")` it might be better to create a `Q.regex()`.

**Comment by aminalaee** [comment]
Hey, thanks for the effort.

I do understand the second part. That makes sense and the `contains` is a shortcut.

But the first part I did not understand. Can you elaborate a bit?

**Comment by MAD-py** [comment]
It's ok. I think I was not clear enough

This is what the MongoDB documentation says.

"To query if the array field contains at least one element with the specified value, use the filter { <field>: <value> } where <value> is the element value."

### Example:
Tags is a list as this: ["Adventure", "Comedy", "Action"]

`db.movie.find( { tags: "Action" } )`

This is the way to search **Action** inside tags,  which literally for us would be

```py
movie = await Movie.query({Movie.tags: "Action"}).all()
```

**Comment by aminalaee** [comment]
Ok yeah I understand that. But what if we want to use the query builder.
For example in queries:

```python
await Movie.query(Movie.yaer == 2005).first()
```

Now for the tags array query these are valid:

```python
await Movie.query({Movie.tags: "Action"}).first()

await Movie.query(Movie.tags == "Action").first()
```
So these should work, even though a bit weird looking.

**Comment by MAD-py** [comment]
That is correct, I have only tested it with the first one but in theory they are equivalent to each other.

My question is if it makes sense to create the `Q.contains` method knowing that it would be the same as this?

In this moment what I have is

```py
    @classmethod
    def contains(cls, key: typing.Any, value: typing.Any) -> QueryExpression:
        if key._pydantic_field.outer_type_ is str:
            return QueryExpression(key=key, operator="$regex", value=value)
        return QueryExpression(key=key, operator="$eq", value=value)
```

This works for lists and strings.

**Comment by aminalaee** [comment]
I think it can be useful, as doing `Movie.query(Movie.tags == "Action")` doesn't look very alright.
I don't see any harm in adding it. What do you think?

**Comment by MAD-py** [comment]
The truth is that I agree with what you say.

I'm going to finish organizing it to upload the PR.
