### ISSUE TITLE
Query builder for magic method `__contains__`

### ISSUE THREAD

**Issue by MAD-py** [aminalaee/mongox#32]
Query within a list type field with `__contains__`

```py
import mongox


class Movie(mongox.Model):
    name: str
    year: int
   tags: List[str]


movies = await Movie.query(Movie.tag in ["A"]).all()
```

**Comment by aminalaee** [comment]
Ok I think we've missed something.

Overriding the `__contains__` does not achieve what we want here.
We won't be able to override the `list` contains method so. when doing `Movie.tag in []` it will always return a boolean and can't be override.
