### ISSUE TITLE
Insert isn't working

### ISSUE THREAD

**Issue by crealityeducation** [aminalaee/mongox#47]
My class
class Minutedsx(mongox.Model, db=db, indexes=ohlcindx):
    tradingsymbol: str
    date: datetime
    open: float
    high: float
    low: float
    close: float

    class Meta:
        collection = db.get_collection("mindsx")

I import it in another class and tried insert in loop. but nothing gets inserted. tried the basic.py in example folder that also didnt insert anything. DB was created though.

**Comment by aminalaee** [comment]
@crealityeducation Any update with this?

**Comment by aminalaee** [comment]
I'll close this but if the issue exists we can re-open this.
